jobs:
  build:
    name: Build and publish
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2.3.5
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: env.SONAR_TOKEN != null && env.SONAR_TOKEN != ''
      name: Cache SonarCloud packages
      uses: actions/cache@v2.1.6
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      id: gradle
      name: Build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: check
        configuration-cache-enabled: true
        dependencies-cache-enabled: true
        wrapper-cache-enabled: true
    - continue-on-error: true
      if: github.event_name == 'pull_request' && failure()
      name: Comment build scan url
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: "github.issues.createComment({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  body: '\u274C\
          \ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url\
          \ }}'\n})\n"
    - continue-on-error: true
      if: always()
      name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      with:
        files: '**/test-results/**/*.xml'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: env.SONAR_TOKEN != null && env.SONAR_TOKEN != ''
      name: Analyze with SonarCloud
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: sonarqube -Psonar.organization=swagger2markup
        configuration-cache-enabled: true
        dependencies-cache-enabled: true
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USER }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      name: Publish to Sonatype
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: publishToSonatype
        configuration-cache-enabled: true
        dependencies-cache-enabled: true
  validation:
    name: Gradle wrapper validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2.3.5
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v1.0.4
name: Build
on:
  repository_dispatch:
    types: trigger-ga___gradle-build.yml
